### ISSUE TITLE
Feature Request: can you make this extension to work on reddit comment links too  

### ISSUE THREAD

**Issue by Droyk** [corbindavenport/peek#1]
**You are about to read some bad English. and I am really sorry about it. I am not a native English speaker.**

Hey corbin,
I have a feature request I want peek to work on reddit comment links too 

I want to request a feature that enables me to press or hover the reddit comment links and read all the comments on the same page 
I am a lazy person..and I am a reddit addict also and I really don't like pressing comments links every damn time to see the damn comments on another tab.

It is a similar feature like Image Expando, Video Expando, Text Expando

Here I made a Image Example with a little help of Photoshop it's not really that good but still you can know what I am talking about http://i.imgur.com/zU8L1z3.png

SO Dev Plz think about this **I Think 80 To 90% Of Users Will Really Like This Feature** 

And it will save their lots of time Just think about it 

**Just Think About It.**
thanx for reading

**Comment by corbindavenport** [comment]
I would implement that, but that would mean Peek would create dozens of popups per page and Chrome would become extremely slow.

**Comment by Droyk** [comment]
what do you mean by popups?

**Comment by corbindavenport** [comment]
The previews Peek generates are the popups.

**Comment by Droyk** [comment]
So add a button to close those popups.
