### ISSUE TITLE
Suggestion: Right-click menu option to preview non-recognised link

### ISSUE THREAD

**Issue by sambooth74** [corbindavenport/peek#12]
A system I use regularly allows users to upload attachments.
The hyperlinks to these attachments have the file extension in the link TEXT, not the URL.

URL example "https://***.com/fileStoreViewer.ashx?FileID=0d47ca6a-6101-495b-a21f-53190e915c4f&CheckID=1287"
Link text example "worddocument.docx"

Would it be possible to either
a) Run pattern matching on the link TEXT (to detect the file extension) as well as the URL
b) Add a right-click menu option to attempt to preview any non-recognised link?

Many thanks!

**Comment by corbindavenport** [comment]
That might be possible. I'm playing around with how the Peek extension could be reworked for the next update, a right-click menu or some other method might be the best way to activate previews in general.

**Comment by corbindavenport** [comment]
The upcoming version of Peek uses CSS selectors for finding links to speed up performance, but unfortunately there's no way to add what you're asking in the new version, because CSS doesn't have a way of filtering links by their text.
