### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by idnovic** [corbindavenport/peek#15]
Please add Firefox support

**Comment by corbindavenport** [comment]
I've actually been working on Firefox support for the next update, it's coming along nicely.

**Comment by idnovic** [comment]
good to hear thank you

**Comment by corbindavenport** [comment]
The Firefox version will be live momentarily: https://addons.mozilla.org/en-US/firefox/addon/peek-preview/

**Comment by corbindavenport** [comment]
The Firefox release is live!
