### ISSUE TITLE
Peek (apparently) breaks an online banking login

### ISSUE THREAD

**Issue by tohaklim** [corbindavenport/peek#2]
Hi Corbin,
Great job on the extension, really helps me out sometimes.
There is this one weird issue, though, which happens when I try to log into my Internet Banking system (in Russian, [https://ibank.belinvestbank.by/signin](link)). As you can see, one of the tabs in the `#signin` element has a PDF, which Peek picks up. Whenever I disable Peek I can login fine, and enabling it gives me an "incorrect username and password" error. 
Any thoughts? Maybe, a per-URL blocklist for Peek could be implemented?

**Comment by corbindavenport** [comment]
Yeah, a blocklist would be a good idea.

**Comment by corbindavenport** [comment]
Chrome now lets you block an extension from accessing a certain site, and implementing a blacklist in Peek on top of that would be confusing (especially since there's no way to sync it with Chrome's own blacklist). Closing this.
