### ISSUE TITLE
Look into Open Document support

### ISSUE THREAD

**Issue by corbindavenport** [corbindavenport/peek#22]
The Google Docs and Office Online viewers don't support OD, but this might work: https://webodf.org/start/

**Comment by locness3** [comment]
Hmm, latest update was in 2015...

**Comment by locness3** [comment]
Anyway tat works so much better then LibreOffice online.

**Comment by locness3** [comment]
Ah no, 6 months ago.

**Comment by corbindavenport** [comment]
It turns out Microsoft's Office Online viewer fully supports most OpenDocument files (odt, ods, and odp). I've added the proper detection code to Peek in the `dev` branch, and the changes will ship in the next update.

![Screenshot from 2021-02-01 12-16-41](https://user-images.githubusercontent.com/3879063/106493823-a9f99200-6487-11eb-8832-d9ff5983f76a.png)
