### ISSUE TITLE
Not working in latest Opera release

### ISSUE THREAD

**Issue by richbordoni** [corbindavenport/peek#27]
Hi, I tried installing Peek 3.0 from the Chrome Web Store, 2.2.1 from the Opera Add-ons site, and 3.1 in developer mode downloaded directly from GitHub but I can't get any of them to work.

2.2.1 and 3.0 don't give me any errors, but 3.1 gives me this error on the chrome://extensions page:
![opera_u9DaJJnxVx](https://user-images.githubusercontent.com/8562062/74284849-998a5d80-4cf2-11ea-80a0-736290024864.png)

I'm on W10 Enterprise x64 Version 2004 and Opera version 66.0.3515.72.

**Comment by richbordoni** [comment]
Upon further testing it looks like Peek (3.1) does have some functionality but is having issues.

- On Google search page .doc and .pdf isn't working
- On some pages the image preview works, and on some pages I get: 
![opera_fKIrgbeJvL](https://user-images.githubusercontent.com/8562062/74288424-5e8c2800-4cfa-11ea-9e22-7223f9b431a0.png)
- I'm often getting a message saying "Peek cannot preview this link because it is served over an unsecure connection" <- not a bug but is there some workaround for this?

 I will continute to test further in the course of my normal browsing and report back with my results.

**Comment by corbindavenport** [comment]
I'll check this out. The unsecure connection issue can't be fixed, it happens when there are HTTP links on HTTPS pages, and rendering previews for those links would cause Mixed Content errors in the web browser.

**Comment by corbindavenport** [comment]
Closing this because Opera is no longer supported: https://blog.corbin.io/post/639975976700379136/im-done-with-opera
