### ISSUE TITLE
Make "Powered by peek" text optional as setting. Maybe remove it for a co-fi.

### ISSUE THREAD

**Issue by cocoonkid** [corbindavenport/peek#36]
Make "Powered by peek" text optional as setting. Maybe remove it for a co-fi.

**Comment by corbindavenport** [comment]
The message helps differentiate Peek popups from any popups the page itself might have. The bottom row also used to have buttons to open the extension settings and pop out the viewer into its own window, which I'm planning to re-implement soon (I just didn't have time after the recent re-write).

**Comment by cocoonkid** [comment]
Thanks for taking the time to explain @corbindavenport . Understood!
