### ISSUE TITLE
security issue prevents preview on http

### ISSUE THREAD

**Issue by samesdat** [corbindavenport/peek#5]
When trying to get previews from http pages there ist no preview but "Peek cannot preview this link because it is served over an insecure connection." Tried with links from the suggested Getting Started page of peek: http://www.google.com/search?as_q=sample&as_filetype=doc

**Comment by corbindavenport** [comment]
This is is a feature in Peek 2.2, which blocks HTTP (insecure) previews on (secure) HTTPS pages. Trying to load insecure content on HTTPS is called [mixed content](https://developers.google.com/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content), and can potentially lead to man-in-the-middle attacks and other problems. Thus, it was disabled in Peek.
