### ISSUE TITLE
Suggestion for new feature: indication of preview- able files

### ISSUE THREAD

**Issue by Marquu** [corbindavenport/peek#7]
Hello,
I would appreciate some indication where the preview- able files are on the web page. Currently you are informed at the peek icon how many files can be previewed but then you proverbially have to try all links to find these previews - this is not very comfortable to say the least.

Thanks.
Marquu

**Comment by corbindavenport** [comment]
Good idea.

**Comment by corbindavenport** [comment]
I wanted to implement this, but I wasn't able to add it in a way where it wouldn't break the appearance of links that already have some kind of background defined in the code.
